name: ci-linux

on:
  push:
    paths:
      - '**'
      - '!docs/**'
      - 'docs/Makefile.am'
      - '!ios/**'
      - '!macos/**'
      - '!msvcstuff/**'
      - '!win32/**'
      - '!AUTHORS'
      - '!ChangeLog'
      - '!COPYING'
      - '!FAQ'
      - '!INSTALL'
      - '!NEWS'
      - '!**README**'
      - '!**.ico'
      - '!**.md'
      - '!**.png'
      - '!**.txt'
      - '!.clang*'
      - '!.gitignore'
      - '!.gitattributes'
      - '!.github/workflows/*'
      - '.github/workflows/ci-linux.yml'
  pull_request:
    paths:
      - '**'
      - '!docs/**'
      - 'docs/Makefile.am'
      - '!ios/**'
      - '!macos/**'
      - '!msvcstuff/**'
      - '!win32/**'
      - '!AUTHORS'
      - '!ChangeLog'
      - '!COPYING'
      - '!FAQ'
      - '!INSTALL'
      - '!NEWS'
      - '!**README**'
      - '!**.ico'
      - '!**.md'
      - '!**.png'
      - '!**.txt'
      - '!.clang*'
      - '!.gitignore'
      - '!.gitattributes'
      - '!.github/workflows/*'
      - '.github/workflows/ci-linux.yml'

jobs:
  irc:
    name: Exult-CI (IRC notification)
    runs-on: ubuntu-18.04
    needs:
      - ci-linux
    if: ${{ always() && (github.repository_owner == 'exult') }}
    steps:
      - name: IRC success notification (ircs://irc.libera.chat:6697/#exult)
        uses: Gottox/irc-message-action@v2
        if: needs.ci-linux.result == 'success'
        with:
          server: irc.libera.chat
          port: 6697
          channel: "#exult"
          nickname: github-actions
          tls: true
          message: "\x0313exult\x03/\x0306${{ github.ref }}\x03 \x0314${{ github.sha }}\x03 https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} The Linux build \x033succeeded\x03."
      - name: IRC failure notification (ircs://irc.libera.chat:6697/#exult)
        uses: Gottox/irc-message-action@v2
        if: needs.ci-linux.result != 'success'
        with:
          server: irc.libera.chat
          port: 6697
          channel: "#exult"
          nickname: github-actions
          tls: true
          message: "\x0313exult\x03/\x0306${{ github.ref }}\x03 \x0314${{ github.sha }}\x03 https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} The Linux build \x034failed\x03."
  ci-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        include:
          - compiler: gcc
            cc: gcc
            cxx: g++
          - compiler: clang
            cc: clang
            cxx: clang++
    steps:
      - name: Install dependencies
        run: |
          sudo apt-fast update
          sudo apt-fast install -y \
          zlib1g-dev libogg-dev libvorbis-dev libasound2-dev libfluidsynth-dev libsdl2-dev libpng-dev libfreetype6-dev libgtk2.0-dev libgtk-3-dev \
          libgdk-pixbuf2.0-dev libxml2-dev bison flex timidity libgimp2.0-dev
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run autogen
        run: |
          chmod a+x ./autogen.sh
          ./autogen.sh
      - name: Configure
        env:
          OVERRIDE_CC: ${{ matrix.cc }}
          OVERRIDE_CXX: ${{ matrix.cxx }}
        run: |
          ./configure --with-debug=extreme --enable-exult-studio --enable-exult-studio-support --enable-compiler --enable-gimp-plugin \
            --enable-zip-support --enable-shared --enable-midi-sfx --enable-gnome-shp-thumbnailer --enable-data --enable-mods \
            --with-usecode-debugger=yes --enable-usecode-container --enable-nonreadied-objects --disable-oggtest --disable-vorbistest
      - name: Build
        run: make -j2
