name: ci-macos

on:
  push:
    paths:
      - "**"
      - "!docs/**"
      - "docs/Makefile.am"
      - "!msvcstuff/**"
      - "!win32/**"
      - "!AUTHORS"
      - "!ChangeLog"
      - "!COPYING"
      - "!FAQ"
      - "!INSTALL"
      - "!NEWS"
      - "!**README**"
      - "!**.ico"
      - "!**.md"
      - "!**.png"
      - "!**.txt"
      - "!.clang*"
      - "!.gitignore"
      - "!.gitattributes"
      - "!.github/workflows/*"
      - ".github/workflows/ci-macos.yml"
  pull_request:
    paths:
      - "**"
      - "!docs/**"
      - "docs/Makefile.am"
      - "!msvcstuff/**"
      - "!win32/**"
      - "!AUTHORS"
      - "!ChangeLog"
      - "!COPYING"
      - "!FAQ"
      - "!INSTALL"
      - "!NEWS"
      - "!**README**"
      - "!**.ico"
      - "!**.md"
      - "!**.png"
      - "!**.txt"
      - "!.clang*"
      - "!.gitignore"
      - "!.gitattributes"
      - "!.github/workflows/*"
      - ".github/workflows/ci-macos.yml"

jobs:
  notify:
    name: Exult-CI (IRC & Discord notification)
    runs-on: ubuntu-latest
    needs:
      - ci-macos
    if: ${{ always() && (github.repository_owner == 'exult' && github.event_name != 'pull_request') }}
    steps:
      - name: IRC success notification (ircs://irc.libera.chat:6697/#exult)
        uses: Gottox/irc-message-action@v2
        if: needs.ci-macos.result == 'success'
        with:
          server: irc.libera.chat
          port: 6697
          channel: "#exult"
          nickname: github-actions
          tls: true
          message: "\x0313exult\x03/\x0306${{ github.ref }}\x03 \x0314${{ github.sha }}\x03 https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} The macOS build \x033succeeded\x03."
      - name: IRC failure notification (ircs://irc.libera.chat:6697/#exult)
        uses: Gottox/irc-message-action@v2
        if: needs.ci-macos.result != 'success'
        with:
          server: irc.libera.chat
          port: 6697
          channel: "#exult"
          nickname: github-actions
          tls: true
          message: "\x0313exult\x03/\x0306${{ github.ref }}\x03 \x0314${{ github.sha }}\x03 https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} The macOS build \x034failed\x03."
      - name: Discord success notification
        uses: rjstone/discord-webhook-notify@v1
        if: needs.ci-macos.result == 'success'
        with:
          severity: info
          username: github-actions
          webhookURL: ${{ secrets.DISCORD_WEBHOOK }}
          text: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          details: 'The macOS build succeeded.'
      - name: Discord failure notification
        uses: rjstone/discord-webhook-notify@v1
        if: needs.ci-macos.result != 'success'
        with:
          severity: error
          username: github-actions
          webhookURL: ${{ secrets.DISCORD_WEBHOOK }}
          text: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          details: 'The macOS build failed.'
  ci-macos:
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: |
          brew update
          brew upgrade
          brew install automake libtool pkg-config libpng zlib libogg libvorbis fluid-synth freetype gtk+3 libxml2 bison flex
          brew install sdl2
      - name: Checkout code
        uses: actions/checkout@master
      - name: Run autogen
        run: |
          chmod a+x ./autogen.sh
          ./autogen.sh
      - name: Configure
        run: |
          export LDFLAGS="-L$(brew --prefix bison)/lib -L$(brew --prefix flex)/lib -L$(brew --prefix zlib)/lib"
          export CPPFLAGS="-I$(brew --prefix flex)/include -I$(brew --prefix zlib)/include"
          export PATH="$(brew --prefix bison)/bin:$(brew --prefix flex)/bin:$(brew --prefix libxml2)/bin:$PATH"
          export PKG_CONFIG_PATH="$(brew --prefix zlib)/lib/pkgconfig:$(brew --prefix libxml2)/lib/pkgconfig"
          ./configure --with-debug=extreme --enable-exult-studio --enable-exult-studio-support --enable-compiler \
            --enable-zip-support --enable-shared --enable-gnome-shp-thumbnailer --enable-data --enable-mods \
            --disable-alsa --disable-timidity-midi --disable-oggtest --disable-vorbistest
      - name: Build
        run: |
          export LDFLAGS="-L$(brew --prefix bison)/lib -L$(brew --prefix flex)/lib -L$(brew --prefix zlib)/lib"
          export CPPFLAGS="-I$(brew --prefix flex)/include -I$(brew --prefix zlib)/include"
          export PATH="$(brew --prefix bison)/bin:$(brew --prefix flex)/bin:$(brew --prefix libxml2)/bin:$PATH"
          export PKG_CONFIG_PATH="$(brew --prefix zlib)/lib/pkgconfig:$(brew --prefix libxml2)/lib/pkgconfig"
          make -j2
