name: ci-windows

on:
  push:
    paths:
      - "**"
      - "!android"
      - "!docs/**"
      - "docs/Makefile.am"
      - "!ios/**"
      - "!macosx/**"
      - "!msvcstuff/**"
      - "!AUTHORS"
      - "!ChangeLog"
      - "!COPYING"
      - "!FAQ"
      - "!INSTALL"
      - "!NEWS"
      - "!**README**"
      - "!**.ico"
      - "!**.md"
      - "!**.png"
      - "!**.txt"
      - "!.clang*"
      - "!.gitignore"
      - "!.gitattributes"
      - "!.github/workflows/*"
      - ".github/workflows/ci-windows.yml"
  pull_request:
    paths:
      - "**"
      - "!android"
      - "!docs/**"
      - "docs/Makefile.am"
      - "!ios/**"
      - "!macosx/**"
      - "!msvcstuff/**"
      - "!AUTHORS"
      - "!ChangeLog"
      - "!COPYING"
      - "!FAQ"
      - "!INSTALL"
      - "!NEWS"
      - "!**README**"
      - "!**.ico"
      - "!**.md"
      - "!**.png"
      - "!**.txt"
      - "!.clang*"
      - "!.gitignore"
      - "!.gitattributes"
      - "!.github/workflows/*"
      - ".github/workflows/ci-windows.yml"

jobs:
  notify:
    name: Exult-CI (IRC & Discord notification)
    runs-on: ubuntu-latest
    needs:
      - ci-windows
    if: ${{ always() && (github.repository_owner == 'exult' && github.event_name != 'pull_request') }}
    steps:
      - name: IRC success notification (ircs://irc.libera.chat:6697/#exult)
        uses: Gottox/irc-message-action@v2
        if: needs.ci-windows.result == 'success'
        with:
          server: irc.libera.chat
          port: 6697
          channel: "#exult"
          nickname: github-actions
          tls: true
          message: "\x0313exult\x03/\x0306${{ github.ref }}\x03 \x0314${{ github.sha }}\x03 https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} The Windows build \x033succeeded\x03."
      - name: IRC failure notification (ircs://irc.libera.chat:6697/#exult)
        uses: Gottox/irc-message-action@v2
        if: needs.ci-windows.result != 'success'
        with:
          server: irc.libera.chat
          port: 6697
          channel: "#exult"
          nickname: github-actions
          tls: true
          message: "\x0313exult\x03/\x0306${{ github.ref }}\x03 \x0314${{ github.sha }}\x03 https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} The Windows build \x034failed\x03."
      - name: Discord success notification
        uses: BubbleProd/discord-webhook-notify@v2.0.1
        if: needs.ci-windows.result == 'success'
        with:
          severity: info
          username: github-actions
          webhookURL: ${{ secrets.DISCORD_WEBHOOK }}
          text: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          title: 'The Windows build succeeded.'
      - name: Discord failure notification
        uses: BubbleProd/discord-webhook-notify@v2.0.1
        if: needs.ci-windows.result != 'success'
        with:
          severity: error
          username: github-actions
          webhookURL: ${{ secrets.DISCORD_WEBHOOK }}
          text: 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          title: 'The Windows build failed.'
  ci-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install:
            base-devel git mingw-w64-x86_64-toolchain mingw-w64-x86_64-binutils mingw-w64-x86_64-ntldd mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-fluidsynth mingw-w64-x86_64-libogg mingw-w64-x86_64-libvorbis mingw-w64-x86_64-munt-mt32emu
            mingw-w64-x86_64-libpng mingw-w64-x86_64-zlib mingw-w64-x86_64-SDL2_image mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-adwaita-icon-theme mingw-w64-x86_64-libxml2 mingw-w64-x86_64-freetype mingw-w64-x86_64-gtk2
            mingw-w64-x86_64-gimp mingw-w64-x86_64-icu
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build
        run: |
          make -j 2 -f Makefile.mingw DEBUG=1 USECODE_CONTAINER=1 USECODE_DEBUGGER=1 SHOW_NONREADIED_OBJECTS=1 Exult.exe exult_studio.exe tools u7shp.exe
          for ff in $(find content -name 'Makefile.mingw' -exec dirname {} \;); do
            pushd "${ff}"
            make -j 2 -f Makefile.mingw
            popd
          done
